---
- name: Download WordPress
  get_url: url=https://fr.wordpress.org/latest-fr_FR.tar.gz dest=/srv/wordpress.tar.gz

- name: Extract archive
  command: chdir=/srv/ /bin/tar xvf wordpress.tar.gz creates=/srv/wordpress

- name: Add group "wordpress"
  group: name=wordpress

- name: Add user "wordpress"
  user: name=wordpress group=wordpress home=/srv/wordpress/

- name: Change ownership of WordPress installation
  file: path=/srv/wordpress/ owner=wordpress group=wordpress state=directory recurse=yes setype=httpd_sys_content_t

