---
- name: installation Mysqls
  yum:
    name: mariadb-server,mariadb,MySQL-python
    state: latest

- name: Make sure a service is running
  systemd:
    state: started
    enabled: yes
    name: mariadb
